name: Frontend-BMI-Calculator

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone your code
      - name: Checkout repository code
        uses: actions/checkout@v4


      # Step 2: Log in to your Docker Hub account
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build the Dockerfile and push it to Docker Hub
      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v6
        with:
          context: . # Looks for the Dockerfile in the root directory
          push: true # Instructs the action to push the image after a successful build
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend-bmi-calculator:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend-bmi-calculator:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend-bmi-calculator:${{ github.sha }}

      
      # ==========================================
      # PHASE 4: CD (REMOTE SERVER DEPLOYMENT)
      # ==========================================
      - name: Deploy application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ubuntu
          key:  ${{ secrets.SSH_PRIVATE_KEY }}
          options: "-o StrictHostKeyChecking=no" 
          script: |
            # Log in to Docker Hub on your remote EC2/VPS server so it has access permissions
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            # Navigate to your deployment folder on the server
            cd /home/ubuntu/app/devops-webapp
            
            # Pull down the latest built image layer and recreate the running container

            docker compose up -d --build --pull always
            # docker compose pull
            # sudo docker compose up -d
            # docker compose up --force-recreate -d   







      # - name: Install dependencies
      #   run: npm install

      # - name: Run lint
      #   run: npm run lint

      # - name: Build project
      #   run: npm run build
